### ISSUE TITLE
Suggestions in lieu of code-review

### ISSUE THREAD

**Issue by usergenic** [namchid/Electron-SSR-Web-Components#15]
* In [_server.js](https://github.com/namchid/Electron-SSR-Web-Components/blob/master/_server.js#L167) It might be nicer to have all the var and function definitions which are currently spread out across multiple JavaScript  execute calls as a separate unified javascript file `_rendererCode.js` ala win.webContents.executeJavaScript(fs.readFileSync(...)).  Referring to the bits like this:

```
  win.webContents.executeJavaScript(`
    function removeScripts(container) {
      var scripts = container.querySelectorAll('script');
      [].slice.call(scripts).forEach(function(el) {
        el.remove();
      });
    }
  `);
```

* Browser Window is [800 x 600](https://github.com/namchid/Electron-SSR-Web-Components/blob/master/_server.js#L26) -- Might be interesting to see approach for implementing client-measured window size for the SSR browser and how that may effect experience for  responsive UIs.

**Comment by namchid** [comment]
Yes! I've been wanting to move those bits outside of `win.webContents.executeJavaScript(...)`, but I wasn't sure how. 

We have seen responsive UI cases where the Browser Window and client window are different sizes. The initial view is based on the Browser Window's, but then it resizes. This isn't ideal, of course; it's on my list of things to do.
